### ISSUE TITLE
App exiting with code 0

### ISSUE THREAD

**Issue by manpreetg** [altso/MBTiles#1]
The app is exiting with code 0. The map is not loading the MBTiles source file.

**Comment by altso** [comment]
Are your talking about GeographyClass sample app?

**Comment by manpreetg** [comment]
Yes. The Geography class. I have tried with new project as well. Select the copy file option from the property for the .mbtiles files. But still facing the same issue. I am using VS2013 version. FYI, I am running the app on the Mobile device of windows and not in the Emulator.

**Comment by manpreetg** [comment]
I am facing the below issue in new project as well :  

Install failed. Rolling back...
Install-Package : Could not install package 'MBTiles 1.0.0.0-alpha'. You are trying to install this package into a project that 
targets '.NETCore,Version=v4.5.1', but the package does not contain any assembly references or content files that are compatible 
with that framework. For more information, contact the package author.
At line:1 char:1
- Install-Package MBTiles -Pre
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
  - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by manpreetg** [comment]
Please ignore the installation issue. Its for only universal apps.

**Comment by manpreetg** [comment]
This is regarding the .mbtiles file permissions. Its resolved now. Thanks. 
and you really did a great a work. Appreciated!! :)

**Comment by altso** [comment]
Glad it's resolved.
