### ISSUE TITLE
The library has not target issues for .NET framework 4.5.1

### ISSUE THREAD

**Issue by manpreetg** [altso/MBTiles#2]
I am facing the below issue in new project as well :

Install failed. Rolling back...
Install-Package : Could not install package 'MBTiles 1.0.0.0-alpha'. You are trying to install this package into a project that
targets '.NETCore,Version=v4.5.1', but the package does not contain any assembly references or content files that are compatible
with that framework. For more information, contact the package author.
At line:1 char:1

```
Install-Package MBTiles -Pre
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    CategoryInfo : NotSpecified: (:) [Install-Package], InvalidOperationException
    FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
```

Will you please add this ?

**Comment by altso** [comment]
What's the type of application you are installing into? I'll be able to look into that on weekends.

**Comment by manpreetg** [comment]
The application is universal app for Tablet and Phone. The VS2013 Express edition.
