### ISSUE TITLE
Project continuation

### ISSUE THREAD

**Issue by xivk** [altso/MBTiles#5]
Hi @altso great job on this library but you don't seem to maintain it currently. Would you be interested in giving me or the group maintaining [NTS](https://github.com/NetTopologySuite/) access to allow the continuation of this project. I want to:

- update it to latest .NET core.
- make sure we can also write MBtiles

I also maintain/co-maintain other geo libraries in the .NET space together with others:
- OsmSharp: https://github.com/osmsharp/
- Itinero: https://github.com/itinero/
- NTS: https://github.com/nettopologysuite

This is one of the missing pieces in the toolset, writing MBTiles using this project:

https://github.com/NetTopologySuite/NetTopologySuite.IO.VectorTiles

The only thing I would need is access to publish nuget pacakges.

**Comment by xivk** [comment]
We would obviously keep you as one of the authors! 👍

**Comment by altso** [comment]
Hi @xivk, this project was designed to work on Windows Phones (RIP) and the code uses types from `Windows.Graphics.Imaging`, `Windows.Storage.Streams`, `Windows.UI.Xaml.Controls.Maps` namespaces. Not sure if all of these exist in .NET Core. It's probably easy to migrate to .NET Standard/Core types thought.

I just added MIT license, so you are free to use any code from this repo.

Hope this helps. Let me know if you need anything else.

**Comment by xivk** [comment]
Oh thanks for your quick response 👍 I would probably heavily refactor the code partially based on this code:

https://github.com/bertt/MBTiles

The goal, to consolidate everything in one package named MBTiles. The main thing I would need is access to publish the nuget package:

https://www.nuget.org/packages/MBTiles/

 My username on nuget is also xivk.

**Comment by altso** [comment]
I'm not comfortable giving you access to publish the nuget package. You will have to publish under a different name.
